.TH "INSTALLER-CLI" "8" "September 2010" "" ""
.SH NAME
installer-cli - installs aptosid live cd onto disk
.SH SYNOPSIS
\fBinstaller-cli\fR \fI<options>
.SH DESCRIPTION
\fBinstaller-cli\fR is minimal textmode GUI to create the config file \fI$HOME/.sidconfig\fR needed by \fBfll-installer\fR for installing a aptosid/fullstory system to disk for use on X-less or GTK2-less systems.
.SH OPTIONS
.TP
\fB\-I\fR \fI<Interface>\fR
Uses \fI<Interface>\fR for the output. Options are \fBtext\fR | \fBdialog\fR
.TP
.B \-h
Print help message.
.TP
.B \-v
Display version information.
.SH EXIT CODES
.TP
\fB0\fR
if successful
.TP
\fB1\fR
if script aborts with errors
.TP
\fB2\fR
if user aborts the script
.SH AUTHORS
Nikolas Poniros (edhunter@aptosid.com) and others.
