.TH "INSTALLER-CLI" "8" "September 2010" "" ""
.SH NAME
installer-cli - Installiert eine aptosid-Live-CD
.SH SYNOPSIS
\fBinstaller-cli\fR \fI<Optionen>\fR
.SH BESCHREIBUNG
\fBinstaller-cli\fR ist ein minimales Terminalprogramm f\(:ur Systeme ohne X oder GTK, welches die Konfigurationsdatei \fI$HOME/.sidconfig\fR erstellt. Diese Datei wird von \fBfll-installer\fR benutzt, um aptosid/fullstory lokal zu installieren.
.SH OPTIONEN
.TP
\fB\-I\fR \fI<Interface>\fR
Benutzt \fI<Interface>\fR f\(:ur die Ausgabe. M\(:ogliche Optionen lauten \fBtext\fR | \fBdialog\fR
.TP
\fB\-h\fR
Hilfe ausgeben
.TP
\fB\-v\fR
Versionsinformationen ausgeben
.SH EXIT CODES
.TP
\fB0\fR
Das Script ist ohne Fehler durchgelaufen.
.TP
\fB1\fR
Das Script wurde mit Fehlern abgebrochen.
.TP
\fB2\fR
Abbruch des Scripts durch Benutzer.
.SH AUTOREN
Nikolas Poniros (edhunter@aptosid.com) und andere.
