.TH "INSTALLER-CLI" 8 "September 2010" "" ""
.SH NAME
installer-cli - install aptosid live cd onto harddisk
.SH SYNOPSIS
\fBinstaller-cli\fR \fI<options>
.SH DESCRIPTION
\fBinstaller-cli\fR creates the config file ($HOME/.sidconfig) needed by the \fBfll-installer\fR and then calls the \fBfll-installer\fR to install aptosid using said config file.
'\".sp
'\"If installed \fBdialog\fR is the default interface. Otherwise \fIreadline\fR is used.
.SH OPTIONS
.TP
\fB\-I\fR \fI<Interface>\fR
Uses \fI<Interface>\fR for the output. Options are \fBtext\fR | \fBdialog\fR
.TP
.B \-h
Print help message.
.TP
.B \-v
Display version information.
.SH EXIT CODES
.TP
\fB0\fR
if successful
.TP
\fB1\fR
if user aborts before the config file is written
.TP
\fB2\fR
if user aborts after config file is written (whenever a user presses OK at an error message it is considered as a user abort even if he has no other choice)
.SH AUTHORS
Nikolas Poniros (edhunter@aptosid.com) and others.
